const month = [
  {
      id: 1,
      day: 1,
      dayOfWeek: 'Qua',
      isAvailable: false,
  },
  {
      id: 2,
      day: 2,
      dayOfWeek: 'Qui',
      isAvailable: false,
  },
  {
      id: 3,
      day: 3,
      dayOfWeek: 'Sex',
      isAvailable: false,
  },
  {
      id: 4,
      day: 4,
      dayOfWeek: 'Sab',
      isAvailable: false,
  },
  {
      id: 5,
      day: 5,
      dayOfWeek: 'Dom',
      isAvailable: false,
  },
  {
      id: 6,
      day: 6,
      dayOfWeek: 'Seg',
      isAvailable: false,
  },
  {
      id: 7,
      day: 7,
      dayOfWeek: 'Ter',
      isAvailable: true,
  },
  {
      id: 8,
      day: 8,
      dayOfWeek: 'Qua',
      isAvailable: true,
  },
  {
      id: 9,
      day: 9,
      dayOfWeek: 'Qui',
      isAvailable: true,
  },
  {
      id: 10,
      day: 10,
      dayOfWeek: 'Sex',
      isAvailable: true,
  },
  {
      id: 11,
      day: 11,
      dayOfWeek: 'Sab',
      isAvailable: true,
  },
  {
      id: 12,
      day: 12,
      dayOfWeek: 'Dom',
      isAvailable: false,
  },
  {
      id: 13,
      day: 13,
      dayOfWeek: 'Seg',
      isAvailable: false,
  },
  {
      id: 14,
      day: 14,
      dayOfWeek: 'Ter',
      isAvailable: true,
  },
  {
      id: 15,
      day: 15,
      dayOfWeek: 'Qua',
      isAvailable: true,
  },
  {
      id: 16,
      day: 16,
      dayOfWeek: 'Qui',
      isAvailable: true,
  },
  {
      id: 17,
      day: 17,
      dayOfWeek: 'Sex',
      isAvailable: true,
  },
  {
      id: 18,
      day: 18,
      dayOfWeek: 'Sab',
      isAvailable: true,
  },
  {
      id: 19,
      day: 19,
      dayOfWeek: 'Dom',
      isAvailable: false,
  },
  {
      id: 20,
      day: 20,
      dayOfWeek: 'Seg',
      isAvailable: false,
  },
  {
      id: 21,
      day: 21,
      dayOfWeek: 'Ter',
      isAvailable: true,
  },
  {
      id: 22,
      day: 22,
      dayOfWeek: 'Qua',
      isAvailable: true,
  },
  {
      id: 23,
      day: 23,
      dayOfWeek: 'Qui',
      isAvailable: true,
  },
  {
      id: 24,
      day: 24,
      dayOfWeek: 'Sex',
      isAvailable: true,
  },
  {
      id: 25,
      day: 25,
      dayOfWeek: 'Sab',
      isAvailable: true,
  },
  {
      id: 26,
      day: 26,
      dayOfWeek: 'Dom',
      isAvailable: false,
  },
  {
      id: 27,
      day: 27,
      dayOfWeek: 'Seg',
      isAvailable: false,
  },
  {
      id: 28,
      day: 28,
      dayOfWeek: 'Ter',
      isAvailable: true,
  },
  {
      id: 29,
      day: 29,
      dayOfWeek: 'Qua',
      isAvailable: true,
  },
  {
      id: 30,
      day: 30,
      dayOfWeek: 'Qui',
      isAvailable: true,
  },
  {
      id: 31,
      day: 31,
      dayOfWeek: 'Sex',
      isAvailable: true,
  },
]

export { month }